[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' https: data:;
      script-src 'self' 'unsafe-inline' https://tally.so https://*.tally.so;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' data: https://fonts.gstatic.com https://wf.typesquare.com;
      frame-src 'self' https://tally.so https://*.tally.so;
      img-src 'self' data: https:;
    """
